# Use official Prometheus image
FROM prom/prometheus:v2.40.0

# Copy the minimal prometheus.yml configuration
COPY prometheus.yml /etc/prometheus/prometheus.yml

# Expose the Prometheus port
EXPOSE 9090

# Run Prometheus with the custom config
CMD [ "--config.file=/etc/prometheus/prometheus.yml" ]
