global:
  scrape_interval: 15s  # Scrape every 15 seconds
rule_files:
  - "alerts.yml"
scrape_configs:
  - job_name: 'monitoring_service'
    static_configs:
      - targets: ['172.19.0.1:8007']  # Replace with your Prometheus service URL
