version: "3.9"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5778:5778"       # Jaeger UI admin endpoint
      - "16686:16686"     # Jaeger UI for tracing
      - "14250:14250"     # Jaeger collector gRPC endpoint
      - "14268:14268"     # Jaeger collector HTTP endpoint   
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    restart: always
    networks:
      - jaeger-net

networks:
  jaeger-net:
    driver: bridge
