version: "3.7"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    networks:
      - otel-net
    ports:
      - "4317:4317"   # OTLP gRPC endpoint
      - "55681:55681" # OTLP HTTP endpoint (if needed)
      - "14251:14250" # Jaeger gRPC endpoint (for communication with your app)
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: >
      --config /etc/otel-collector-config.yaml
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - otel-net
    ports:
      - "5775:5775"  # Jaeger Agent
      - "6831:6831/udp" # Jaeger Agent (UDP)
      - "6832:6832/udp" # Jaeger Agent (UDP)
      - "5778:5778"   # Jaeger Agent HTTP
      - "14250:14250" # Jaeger gRPC
      - "14268:14268" # Jaeger HTTP
      - "16686:16686" # Jaeger UI (for the web interface)
      - "14224:14224" # Jaeger Thrift HTTP
    restart: always

networks:
  otel-net:
    driver: bridge
